import type { Metadata } from "next";
import "./globals.css";
import TopNav from "@/components/navbar/TopNav";
import { Providers } from "./providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
      <Providers>
      <TopNav />
      <main className="container mx-auto">{children}</main>
      </Providers>
      </body>
    </html>
  );
}
